server:
  port: 7003
spring:
  application:
    name: jeecg-cms


  rabbitmq:
    host: 192.168.101.14
    port: 5672
    username: admin
    password: admin
    connection-timeout: 60s
    listener:
      direct:
        acknowledge-mode: none
